"""add task estimate hours

Revision ID: aebbaa09a1bc
Revises: 3dd58abcb2b8
Create Date: 2026-08-13 10:24:42.943370

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aebbaa09a1bc"
down_revision: Union[str, Sequence[str], None] = "3dd58abcb2b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("estimate_hours", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "estimate_hours")
    # ### end Alembic commands ###
